'use strict';
const $=id=>document.getElementById(id);
let token=location.hash.slice(1)||sessionStorage.getItem('organizer-token')||'';
if(token){sessionStorage.setItem('organizer-token',token);history.replaceState(null,'',location.pathname);}
let device='',base=null,draft=null,undoStack=[],selected=new Set(),expanded=new Set(),dragPath=null,activeTab='layout',apps=[],choices={},sortHistory=[],plan=null,busy=false,saveTimer=null,saveChain=Promise.resolve();
const clone=x=>structuredClone(x);
let iconImages={},pendingIcons=new Set(),wallpaperImage=null;
async function loadWallpaper(){const target=device;const result=await api('layout.wallpaper',{device_id:target});if(device!==target)return;if(wallpaperImage)URL.revokeObjectURL(wallpaperImage);wallpaperImage=null;if(result.available){const decoded=atob(result.image.split(',')[1]),bytes=new Uint8Array(decoded.length);for(let n=0;n<decoded.length;n++)bytes[n]=decoded.charCodeAt(n);wallpaperImage=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));}document.documentElement.style.setProperty('--phone-wallpaper',wallpaperImage?'url("'+wallpaperImage+'")':'none');$('wallpaperStatus').textContent=result.available?'From your iPhone':result.reason;$('showWallpaper').disabled=!result.available;renderBoards();}
function showSortIcon(current){const node=$('sortIcon');node.replaceChildren();if(!current){node.textContent=apps.length?'✓':'–';return;}const image=iconImages[current.identifier];if(image){const img=element('img',undefined,'appimage');img.alt='';img.src=image;node.append(img);return;}node.textContent=current.name.slice(0,2).toUpperCase();const key=device+':'+current.identifier;if(pendingIcons.has(key))return;pendingIcons.add(key);const target=device;api('apps.icons',{device_id:target,identifiers:[current.identifier]}).then(result=>{if(device!==target)return;Object.assign(iconImages,result.icons);if(nextApp()?.identifier===current.identifier&&result.icons[current.identifier])showSortIcon(current);}).catch(()=>{}).finally(()=>pendingIcons.delete(key));}
const appleApp=id=>id==='com.apple'||id.startsWith('com.apple.');
function iconImage(item){const id=item.identifier||item.key;const image=element('img',undefined,'appimage');image.alt='';image.draggable=false;image.src=iconImages[id]||'';return image;}
async function loadIcons(live){const targetDevice=device,ids=new Set();const visit=items=>items.forEach(x=>folder(x)?x.pages.forEach(visit):ids.add(x.identifier||x.key));visit(live.dock);live.pages.forEach(visit);const list=[...ids].filter(Boolean);for(let n=0;n<list.length;n+=24){const result=await api('apps.icons',{device_id:targetDevice,identifiers:list.slice(n,n+24)});if(device!==targetDevice)return;Object.assign(iconImages,result.icons);renderBoards();}notice('Home Screen loaded with app icons from your iPhone.');}
const folder=x=>x.kind==='folder';
function ask(message,initial=null){return new Promise(resolve=>{const dialog=$('inputDialog'),input=$('inputValue'),accept=$('inputAccept'),cancel=$('inputCancel');$('inputTitle').textContent=initial===null?'Confirm':'Folder name';$('inputMessage').textContent=message;input.hidden=initial===null;input.value=initial||'';input.disabled=false;accept.disabled=cancel.disabled=false;accept.textContent=initial===null?'Continue':'Save';const finish=value=>{dialog.removeEventListener('cancel',escape);accept.onclick=cancel.onclick=null;input.onkeydown=null;dialog.close();resolve(value);};const escape=e=>{e.preventDefault();finish(null);};dialog.addEventListener('cancel',escape);cancel.onclick=()=>finish(null);accept.onclick=()=>{if(initial!==null&&!input.value.trim()){input.focus();return;}finish(initial===null?true:input.value.trim());};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();accept.click();}};dialog.showModal();if(initial!==null)input.focus();});}
const askText=(message,value='')=>ask(message,value);
const confirmChoice=async message=>Boolean(await ask(message));
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
async function api(name,args={}){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({name,arguments:args})});const value=await r.json();if(!r.ok)throw Error(value.error||'The request failed.');return value;}
async function task(fn){if(busy)return;busy=true;document.querySelectorAll('button,select,input').forEach(b=>b.dataset.wasDisabled=b.disabled?'1':'0');document.querySelectorAll('button,select,input').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;document.querySelectorAll('button,select,input').forEach(b=>{b.disabled=b.dataset.wasDisabled==='1';delete b.dataset.wasDisabled;});if(draft)renderBoards();renderSorter();$('applyPlan').disabled=!$('approve').checked;}}
function needDevice(){if(!device)throw Error('Select an attached iPhone first.');}
function get(path){return path.reduce((value,key)=>value[key],draft);}
function walk(callback){if(!draft)return;const visit=(arr,path)=>arr.forEach((x,i)=>{const p=[...path,i];callback(x,p);if(folder(x))x.pages.forEach((page,n)=>visit(page,[...p,'pages',n]));});visit(draft.dock,['dock']);draft.pages.forEach((p,n)=>visit(p,['pages',n]));}
function findKey(key){let found;walk((x,path)=>{if(x.key===key)found=path;});return found;}
function protectedPath(path){return path[0]==='dock'?$('protectDock').checked:path[1]===0&&$('protectPage').checked;}
function clean(){function cleanArray(arr){for(let i=arr.length-1;i>=0;i--){if(folder(arr[i])){arr[i].pages.forEach(cleanArray);arr[i].pages=arr[i].pages.filter(p=>p.length);if(!arr[i].pages.length)arr.splice(i,1);}}}draft.pages.forEach(cleanArray);cleanArray(draft.dock);draft.pages=draft.pages.filter((p,n)=>p.length||n===0);}
function stash(){if(!draft)return;try{if(!undoStack.length&&JSON.stringify(draft)===JSON.stringify(base)){localStorage.removeItem('organizer-draft:'+device);return;}localStorage.setItem('organizer-draft:'+device,JSON.stringify({baseRevision:base.revision,draft,undoStack}));}catch(e){notice('Browser draft saving is unavailable. Review and save a staged plan to retain it.',true);}}
function edit(fn){if(busy||!draft)return;const prior=clone(draft);try{fn();clean();undoStack.push(prior);if(undoStack.length>30)undoStack.shift();plan=null;stash();renderBoards();notice('Draft updated. Review changes before applying them to the iPhone.');}catch(e){draft=prior;notice(e.message,true);}}
function move(from,to,index){edit(()=>{if(protectedPath(from)||protectedPath(to))throw Error('That page or dock is protected.');if(to.length>=from.length&&from.every((v,i)=>to[i]===v))throw Error('A folder cannot be moved inside itself.');const source=get(from.slice(0,-1)),item=get(from),dest=get(to),anchor=dest[index],parentPages=to.length>2?get(to.slice(0,-1)):null;if(item===anchor)return;if(folder(item)&&to.includes('pages')&&to.length>2)throw Error('Folders cannot contain folders.');source.splice(from.at(-1),1);let at=anchor?dest.indexOf(anchor):dest.length;if(at<0)at=dest.length;dest.splice(at,0,item);if(to.length===1&&dest.length>4||to.length===2&&dest.length>24)throw Error('The destination is full.');if(to.length>2&&dest.length>9){const spill=dest.splice(9);parentPages.splice(to.at(-1)+1,0,spill);}});}
function element(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function button(text,fn,className='small'){const b=element('button',text,className);b.onclick=fn;return b;}
function dropZone(node,to,index){node.addEventListener('dragover',e=>{if(busy||protectedPath(to))return;e.preventDefault();node.classList.add('dragover');});node.addEventListener('dragleave',()=>node.classList.remove('dragover'));node.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();node.classList.remove('dragover');if(dragPath)move(dragPath,to,index);dragPath=null;});}
function iconNode(item,path){const slot=element('div',undefined,'slot'+(folder(item)?' folder':''));const icon=element('button',undefined,'icon'+(selected.has(item.key)?' selected':''));const glyph=element('span',folder(item)?'▦':item.name.slice(0,2).toUpperCase(),'glyph');if(!folder(item)){let hue=0;for(const c of item.key||item.name)hue=(hue*31+c.charCodeAt(0))%360;glyph.style.backgroundColor='hsl('+hue+' 35% 35%)';}if(folder(item)){glyph.textContent='';glyph.classList.add('folderpreview');for(const child of item.pages.flat().slice(0,9)){const mini=element('span',undefined,'miniicon');if(iconImages[child.identifier||child.key])mini.append(iconImage(child));else mini.textContent=child.name.slice(0,1);glyph.append(mini);}}else if(iconImages[item.identifier||item.key]){glyph.textContent='';glyph.append(iconImage(item));}icon.append(glyph,element('span',item.name));icon.title=folder(item)?'Open folder':item.name+' · '+(item.identifier||item.key);icon.draggable=!protectedPath(path)&&!busy;icon.addEventListener('dragstart',e=>{dragPath=path;e.dataTransfer.setData('text/plain',JSON.stringify(path));e.dataTransfer.effectAllowed='move';});icon.addEventListener('dragend',()=>dragPath=null);icon.onclick=()=>{if(folder(item)){const key=JSON.stringify(path);expanded.has(key)?expanded.delete(key):expanded.add(key);renderBoards();}else if(!protectedPath(path)){selected.has(item.key)?selected.delete(item.key):selected.add(item.key);renderBoards();}};icon.setAttribute('aria-label',folder(item)?'Open '+item.name+' folder':item.name+(protectedPath(path)?', protected':', select to move'));if(!folder(item))icon.setAttribute('aria-pressed',selected.has(item.key)?'true':'false');slot.append(icon);dropZone(slot,path.slice(0,-1),path.at(-1));if(folder(item)){icon.addEventListener('dragover',e=>{if(!dragPath||protectedPath(path)||folder(get(dragPath)))return;e.preventDefault();e.stopPropagation();slot.classList.add('dragover');});icon.addEventListener('drop',e=>{if(!dragPath||folder(get(dragPath)))return;e.preventDefault();e.stopPropagation();move(dragPath,[...path,'pages',item.pages.length-1],item.pages.at(-1).length);dragPath=null;});}return slot;}
function folderBody(item,path){const body=element('div',undefined,'folderbody');const head=element('div',undefined,'foldertitle');head.append(element('strong',item.name),button('Rename',async()=>{if(protectedPath(path)){notice('This page is protected.',true);return;}const name=await askText('Folder name',item.name);if(name?.trim())edit(()=>get(path).name=name.trim());}));body.append(head);item.pages.forEach((page,n)=>{body.append(element('p','Folder page '+(n+1),'muted'));const grid=element('div',undefined,'folderpage');page.forEach((x,i)=>grid.append(iconNode(x,[...path,'pages',n,i])));const end=element('div','Drop into folder','dropend');dropZone(end,[...path,'pages',n],page.length);grid.append(end);body.append(grid);});return body;}
function board(arr,path,title){const protectedBoard=protectedPath(path),isDock=path[0]==='dock';const node=element('section',undefined,'board'+(protectedBoard?' protected':''));const head=element('div',undefined,'boardhead');head.append(element('strong',title),element('span',protectedBoard?'Protected':arr.length+' entries'));node.append(head);const grid=element('div',undefined,'grid phonegrid'+(wallpaperImage&&$('showWallpaper').checked?' has-wallpaper':''));arr.forEach((x,i)=>grid.append(iconNode(x,[...path,i])));for(let n=arr.length;n<(isDock?4:24);n++){const empty=element('div',undefined,'slot empty-slot');empty.title='Empty position '+(n+1);empty.append(element('span',undefined,'empty-glyph'));dropZone(empty,path,arr.length);grid.append(empty);}node.append(grid);if(!isDock){const end=element('div',protectedBoard?'Protected from edits':'Drop at end','dropend');dropZone(end,path,arr.length);node.append(end);}return node;}
function renderBoards(){if(!draft){$('boards').replaceChildren();$('dock').replaceChildren();$('folderTray').replaceChildren();return;}$('boards').replaceChildren(...draft.pages.map((p,n)=>board(p,['pages',n],'Page '+(n+1))));$('dock').replaceChildren(board(draft.dock,['dock'],'Dock'));$('folderTray').replaceChildren();walk((item,path)=>{if(folder(item)&&expanded.has(JSON.stringify(path))){const body=folderBody(item,path);body.querySelector('.foldertitle').append(button('Close',()=>{expanded.delete(JSON.stringify(path));renderBoards();}));$('folderTray').append(body);}});$('layoutSummary').textContent=draft.pages.length+' pages · '+(JSON.stringify(draft)===JSON.stringify(base)?'Live layout':'Unsaved draft');$('selectedCount').textContent=selected.size+' selected';$('undoDraft').disabled=!undoStack.length;$('makeFolder').disabled=!selected.size;$('moveSelected').disabled=selected.size!==1;const value=$('movePage').value;$('movePage').replaceChildren(...draft.pages.map((p,n)=>{const o=element('option','Page '+(n+1));o.value=n;return o;}));if(value!==''&&Number(value)<draft.pages.length)$('movePage').value=value;}
async function readLayout(){needDevice();if(draft&&undoStack.length&&!(await confirmChoice('Discard the current draft and reload from the phone?')))return;notice('Reading Home Screen layout…');const live=await api('layout.read',{device_id:device});base=clone(live);draft=clone(live);undoStack=[];selected.clear();expanded.clear();try{const saved=JSON.parse(localStorage.getItem('organizer-draft:'+device)||'null');if(saved&&saved.baseRevision===live.revision&&JSON.stringify(saved.draft)!==JSON.stringify(live)&&(await confirmChoice('Restore your saved draft?'))){draft=saved.draft;undoStack=saved.undoStack||[];}}catch(e){}renderBoards();notice('Reading app icons from the iPhone…');await loadIcons(live);try{await loadWallpaper();}catch(e){$('wallpaperStatus').textContent='Wallpaper unavailable. Refresh layout to retry.';}}
async function findDevices(){const value=await api('devices.list');const previous=device;$('device').replaceChildren(element('option','Select your iPhone'));$('device').firstChild.value='';for(const d of value.devices){const o=element('option',d.name+(d.ios?' · iOS '+d.ios:'')+(d.available?'':' · unlock and trust'));o.value=d.id;$('device').append(o);}if(previous&&value.devices.some(d=>d.id===previous))$('device').value=previous;$('connectionStatus').textContent=value.devices.length?value.devices.length+' device(s) detected':'No device found. Check USB, unlock, and Apple device support.';if(value.devices.length===1&&!device){$('device').value=value.devices[0].id;device=value.devices[0].id;await readLayout();}}
function openPlan(value){plan=value;$('reviewTitle').textContent=value.kind==='delete'?'Review app deletion':'Review Home Screen changes';$('reviewSummary').textContent=value.summary;$('reviewContent').replaceChildren();if(value.kind==='delete'){for(const app of value.apps){const row=element('div',app.name,'row');row.append(element('small',app.identifier));$('reviewContent').append(row);}}else{const protectedInfo=value.protected;$('reviewContent').append(element('p','Page one: '+(protectedInfo.page_one?'protected':'editable')+' · Dock: '+(protectedInfo.dock?'protected':'editable')));for(const change of value.changes){const row=element('div',undefined,'row');const label=element('div',change.name);label.append(element('small',change.from+' → '+change.to));$('reviewContent').append(row);row.append(label);}if(!value.changes.length)$('reviewContent').append(element('p','No icon positions change. Folder names or structure may still change.'));}$('approve').checked=false;$('applyPlan').disabled=true;$('review').showModal();}
async function previewLayout(){needDevice();if(!draft)throw Error('Read the current layout first.');clean();openPlan(await api('layout.plan',{device_id:device,base_revision:base.revision,layout:draft,protect_page_one:$('protectPage').checked,protect_dock:$('protectDock').checked}));}
async function applyPlan(){if(!plan||!$('approve').checked)return;notice('Applying the reviewed plan and verifying the phone. Keep the USB cable connected…');const result=await api('changes.apply',{plan_id:plan.id,confirmed:true});$('review').close();if(result.status==='verified'){if(result.layout){base=clone(result.layout);draft=clone(result.layout);undoStack=[];selected.clear();localStorage.removeItem('organizer-draft:'+device);renderBoards();}else{apps=[];await readApps();}notice('Verified: the changes saved on your iPhone. Original Home Screen layout backed up.');}else{notice('Result: '+result.status+'. '+(result.error||'The saved phone state differs from the plan. Review operation history before retrying.'),true);}await readHistory();}
function download(name,value,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([value],{type}));const a=element('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function readApps(){needDevice();notice('Reading installed apps'+($('sizes').checked?' and storage sizes':'')+'…');const [inventory,progress]=await Promise.all([api('apps.list',{device_id:device,calculate_sizes:$('sizes').checked}),api('choices.read',{device_id:device})]);apps=inventory.apps.filter(a=>!appleApp(a.identifier));choices=progress.choices||{};sortHistory=progress.history||[];try{const local=JSON.parse(localStorage.getItem('organizer-sort:'+device)||'null');if(local&&local.savedAt>(progress.savedAt||0)){choices=local.choices;sortHistory=local.history;await api('choices.save',{device_id:device,choices,history:sortHistory});}}catch(e){}choices=Object.fromEntries(Object.entries(choices).filter(([id])=>!appleApp(id)));sortHistory=sortHistory.filter(h=>!appleApp(h.identifier));renderSorter();notice('Loaded '+apps.length+' apps for sorting. Apple com.apple apps are excluded.');}
function saveSort(){try{localStorage.setItem('organizer-sort:'+device,JSON.stringify({choices,history:sortHistory,savedAt:Date.now()}));}catch(e){}clearTimeout(saveTimer);const values=clone({device_id:device,choices,history:sortHistory});saveTimer=setTimeout(()=>{saveChain=saveChain.catch(()=>{}).then(()=>api('choices.save',values)).catch(e=>notice('Progress could not be saved to the workspace: '+e.message,true));},200);}
function decide(id,value){if(busy||appleApp(id))return;sortHistory.push({identifier:id,before:choices[id]||null});choices[id]=value;saveSort();renderSorter();}
function shownApps(){return apps.filter(a=>$('appScope').value==='Any'||a.type===$('appScope').value);}
function nextApp(){return shownApps().find(a=>!choices[a.identifier]);}
function renderSorter(){const shown=shownApps(),current=nextApp(),done=shown.filter(a=>choices[a.identifier]).length,kept=apps.filter(a=>choices[a.identifier]==='keep').length,deleted=apps.filter(a=>choices[a.identifier]==='delete').length;$('appSummary').textContent=shown.length+' shown / '+apps.length+' eligible apps · '+kept+' kept · '+deleted+' marked for deletion';showSortIcon(current);$('sortMeter').max=Math.max(1,shown.length);$('sortMeter').value=done;$('sortProgress').textContent=apps.length?done+' / '+shown.length+' reviewed':'Read the app inventory to begin.';$('sortName').textContent=current?current.name:apps.length?'All reviewed!':'Keep what matters.';$('sortId').textContent=current?current.identifier:'';$('sortDetails').textContent=current?(current.type||'App')+(current.total_gib!==null?' · '+current.total_gib.toFixed(3)+' GiB':''):'';$('keep').disabled=$('delete').disabled=!current||busy;$('undoSort').disabled=!sortHistory.length||busy;$('previewDeletes').disabled=!deleted||busy;const term=$('appSearch').value.toLowerCase();$('appList').replaceChildren();for(const app of shown.filter(a=>(a.name+' '+a.identifier).toLowerCase().includes(term))){const row=element('div',undefined,'row');const label=element('div',app.name,'label');label.append(element('small',app.identifier));if(choices[app.identifier])label.append(element('small','Choice: '+choices[app.identifier]));const controls=element('div',undefined,'toolbar');controls.append(button('Keep',()=>decide(app.identifier,'keep')),button('Delete',()=>decide(app.identifier,'delete')));const identity=element('div',undefined,'inventory-label');if(iconImages[app.identifier]){const img=element('img',undefined,'inventory-icon');img.src=iconImages[app.identifier];img.alt='';identity.append(img);}identity.append(label);row.append(identity,controls);$('appList').append(row);}}
function undoSort(){if(!sortHistory.length||busy)return;const last=sortHistory.pop();if(last.before===null)delete choices[last.identifier];else choices[last.identifier]=last.before;saveSort();renderSorter();}
function exportChoices(value){download(value+'.txt',apps.filter(a=>choices[a.identifier]===value).map(a=>a.name+'\t'+a.identifier).join('\r\n')+'\r\n');}
async function previewDeletes(){needDevice();const ids=apps.filter(a=>choices[a.identifier]==='delete').map(a=>a.identifier);if(!ids.length)throw Error('No apps are marked for deletion.');openPlan(await api('apps.plan_delete',{device_id:device,identifiers:ids}));}
async function readHistory(){const [backups,history,plans]=await Promise.all([api('layouts.list_backups',device?{device_id:device}:{}),api('history.list'),api('changes.list')]);$('backupList').replaceChildren();for(const b of backups.backups){const row=element('div',undefined,'row');const label=element('div',new Date(b.created*1000).toLocaleString());label.append(element('small',b.pages+' pages · '+b.items+' items'));row.append(label,button('Preview restore',()=>task(async()=>{needDevice();openPlan(await api('layouts.plan_restore',{device_id:device,backup_id:b.id,protect_page_one:$('protectPage').checked,protect_dock:$('protectDock').checked}));})));$('backupList').append(row);}if(!backups.backups.length)$('backupList').append(element('p','Save a layout backup from Home Screen to keep a copy of your current arrangement.','empty-state'));$('historyList').replaceChildren();for(const op of history.operations){const row=element('div',undefined,'row');const label=element('div',(op.kind==='layout'?'Layout change':'App deletion')+' · '+op.status);label.append(element('small',new Date(op.created*1000).toLocaleString()+(op.error?' · '+op.error:'')));row.append(label,button('Download report',()=>download('operation-report.json',JSON.stringify(op,null,2),'application/json')));$('historyList').append(row);}$('planList').replaceChildren();for(const p of plans.plans.filter(p=>p.status==='staged'&&(!device||p.device_id===device))){const row=element('div',undefined,'row');row.append(element('div',p.summary),button('Review',()=>openPlan(p)));$('planList').append(row);}}
async function setupMcp(){const r=await fetch('/mcp',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})});const result=await r.json();$('toolList').replaceChildren(...result.result.tools.map(t=>{const row=element('div',undefined,'row');const label=element('div',t.name);label.append(element('small',t.description));row.append(label);return row;}));const config=await apiConfig();$('mcpConfig').textContent=JSON.stringify(config,null,2);$('downloadConfig').onclick=()=>download('iphone-organizer-mcp.json',JSON.stringify(config,null,2),'application/json');}
async function apiConfig(){const r=await fetch('/config',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Could not load the assistant configuration.');return r.json();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==activeTab);document.querySelectorAll('[data-tab]').forEach(v=>{v.classList.toggle('active',v===b);if(v===b)v.setAttribute('aria-current','page');else v.removeAttribute('aria-current');});if(activeTab==='history')task(readHistory);if(activeTab==='mcp')task(setupMcp);if(activeTab==='apps'&&device&&!apps.length)task(readApps);});
$('refreshDevices').onclick=()=>task(findDevices);$('device').onchange=async()=>{if(busy)return;if(draft&&undoStack.length&&!(await confirmChoice('Switch devices? Your current draft is saved in this browser.'))){$('device').value=device;return;}device=$('device').value;iconImages={};if(wallpaperImage)URL.revokeObjectURL(wallpaperImage);wallpaperImage=null;document.documentElement.style.removeProperty('--phone-wallpaper');$('wallpaperStatus').textContent='Read layout to load wallpaper';base=draft=null;undoStack=[];selected.clear();apps=[];choices={};sortHistory=[];renderBoards();renderSorter();if(device)task(readLayout);};
$('readLayout').onclick=()=>task(readLayout);$('previewLayout').onclick=()=>task(previewLayout);$('undoDraft').onclick=()=>{if(undoStack.length){draft=undoStack.pop();selected.clear();stash();renderBoards();notice('Draft step undone.');}};
$('showWallpaper').onchange=renderBoards;
$('protectPage').onchange=$('protectDock').onchange=()=>{selected.clear();renderBoards();};$('addPage').onclick=()=>{if(!draft){notice('Read the layout first.',true);return;}if(draft.pages.length>=15){notice('Maximum supported page count reached.',true);return;}undoStack.push(clone(draft));draft.pages.push([]);stash();renderBoards();notice('New draft page added. Move an icon onto it before reviewing.');};
$('clearSelection').onclick=()=>{selected.clear();renderBoards();};$('moveSelected').onclick=()=>{if(selected.size!==1)return;const from=findKey([...selected][0]);move(from,['pages',Number($('movePage').value)],Number($('movePosition').value)-1);selected.clear();renderBoards();};
$('makeFolder').onclick=async()=>{if(!selected.size)return;const name=await askText('Name for the new folder');if(!name?.trim())return;const pageIndex=Number($('movePage').value);edit(()=>{if(protectedPath(['pages',pageIndex]))throw Error('The destination page is protected.');const icons=[];for(const key of selected){const path=findKey(key);if(!path||protectedPath(path))throw Error('A selected icon is protected or unavailable.');const item=get(path);if(item.special)throw Error('Keep special icons outside folders.');icons.push(item);get(path.slice(0,-1)).splice(path.at(-1),1);}const pages=[];for(let i=0;i<icons.length;i+=9)pages.push(icons.slice(i,i+9));draft.pages[pageIndex].push({kind:'folder',name:name.trim(),pages});if(draft.pages[pageIndex].length>24)throw Error('That page is full.');selected.clear();});};
$('backupNow').onclick=()=>task(async()=>{needDevice();await api('layouts.backup',{device_id:device});notice('Current Home Screen layout backed up in the portable workspace.');});
$('readApps').onclick=()=>task(readApps);$('keep').onclick=()=>{const a=nextApp();if(a)decide(a.identifier,'keep');};$('delete').onclick=()=>{const a=nextApp();if(a)decide(a.identifier,'delete');};$('undoSort').onclick=undoSort;$('exportKeep').onclick=()=>exportChoices('keep');$('exportDelete').onclick=()=>exportChoices('delete');$('previewDeletes').onclick=()=>task(previewDeletes);$('appSearch').oninput=renderSorter;$('appScope').onchange=renderSorter;
$('backupSort').onclick=()=>download('sorting-progress.json',JSON.stringify({version:1,device_id:device,choices,history:sortHistory},null,2),'application/json');
$('restoreSort').onchange=e=>task(async()=>{try{needDevice();const file=e.target.files[0];if(!file)return;const value=JSON.parse(await file.text());const ids=new Set(apps.map(a=>a.identifier));if(value.version!==1||value.device_id!==device||!value.choices||Array.isArray(value.choices)||Object.entries(value.choices).some(([id,v])=>!ids.has(id)||!['keep','delete'].includes(v))||!Array.isArray(value.history)||value.history.some(h=>!h||!ids.has(h.identifier)||![null,'keep','delete'].includes(h.before)))throw Error('This progress file does not match this phone and inventory.');choices=value.choices;sortHistory=value.history;saveSort();renderSorter();notice('Sorting progress restored.');}finally{e.target.value='';}});
$('importDelete').onchange=e=>task(async()=>{try{needDevice();const file=e.target.files[0];if(!file)return;if(!apps.length)throw Error('Read installed apps first.');const lines=(await file.text()).replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());const ids=lines.map(l=>{const tab=l.lastIndexOf('\t');if(tab<0)throw Error('Use the exported delete.txt format: app name, tab, Identifier.');return l.slice(tab+1);});const known=new Set(apps.map(a=>a.identifier));if(ids.some(appleApp))throw Error('Apple com.apple apps are excluded from deletion.');if(ids.some(id=>!known.has(id))||new Set(ids).size!==ids.length)throw Error('The list contains unknown or repeated Identifiers.');for(const id of ids){sortHistory.push({identifier:id,before:choices[id]||null});choices[id]='delete';}saveSort();renderSorter();notice(ids.length+' apps marked for deletion. Review the uninstall list to apply.');}finally{e.target.value='';}});
$('resetSort').onclick=async()=>{if(await confirmChoice('Clear all sorting choices? Export progress first if you want to retain them.')){choices={};sortHistory=[];saveSort();renderSorter();}};
document.addEventListener('keydown',e=>{if(activeTab!=='apps'||busy||$('review').open||e.repeat||e.altKey||e.target.closest('input,textarea,select,[contenteditable]'))return;const key=e.key.toLowerCase();if(key==='z'){e.preventDefault();undoSort();}else if(!e.ctrlKey&&!e.metaKey&&['k','d'].includes(key)){e.preventDefault();const a=nextApp();if(a)decide(a.identifier,key==='k'?'keep':'delete');}});
$('approve').onchange=()=>{$('applyPlan').disabled=!$('approve').checked;};$('closeReview').onclick=()=>{if(!busy)$('review').close();};$('applyPlan').onclick=()=>task(applyPlan);$('readHistory').onclick=()=>task(readHistory);$('stopServer').onclick=()=>task(async()=>{await fetch('/shutdown',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:'{}'});notice('Organizer stopped. Use Start Organizer to open it again.');});
if(token)task(findDevices);else notice('Open this application through Start Organizer to authenticate.',true);



